spring:
  application:
    name: ciams

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: invuser
    password: inventorypsw
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

server:
  port: 8080
